hit_filename: hit.yaml
aws:
  access_key_id: ''
  secret_access_key: ''
  region_name: 'us-east-1'
mturk:
  endpoint_url: 'https://mturk-requester-sandbox.us-east-1.amazonaws.com'
  preview_url: 'https://workersandbox.mturk.com/mturk/preview?groupId='
tasks:
  - stepbystep:
      template: templates/
      title: ''
      description: ''
      keywords: ''
      reward: 0.15
      max_assignements: 1000
      lifetime: 172800,
      assignement_duration: 60
      auto_approval_delay: 14400
